services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
  mongodbi_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_URL=${MONGO_URI}
    volumes:
      - mongodb-data:/data/db
  server:
    build: ./
    ports:
      - "5000:5000"

volumes:
  mongodb-data:


